import '../globals.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function WriteLayout({children}: {children: React.ReactNode}) {
  return <div>{children}</div>;
}
