import React from 'react';
import '../globals.scss';
import style from '../page.module.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function WriteLayout({children}: {children: React.ReactNode}) {
  return <main className={style.main}>{children}</main>;
}
